---
redis:
  host: redis
  port: 6379
s3:
  bucket: 98106a91-edae-4dbd-8fe3-daf39f28999b
  key_prefix: '%k/%Y/%m/%d'
google_api:
  token_path: google-api-token.pickle
sniffer:
  logging:
    level: INFO
    max_entries: 100
game_abstract_archiver:
  logging:
    level: INFO
    max_entries: 100
game_abstract_crawler:
  logging:
    level: INFO
    max_entries: 100
