logging:
  level: INFO
  log_file:
    path: output/mahjongsoul_sniffer.log
    max_bytes: 10485760
    backup_count: 10
game_abstract:
  storage:
    type: aws_s3
    bucket_name: 98106a91-edae-4dbd-8fe3-daf39f28999b
    key_prefix: game_abstract/%Y/%m/%d
