volumes:
  opt:
  log:
  srv:

services:
  redis:
    image: redis
  web_server:
    build:
      context: ..
      dockerfile: api-visualizer/web-server.Dockerfile
    image: mahjongsoul-api-visualizer-web-server
    volumes:
      - type: volume
        source: opt
        target: /opt/mahjongsoul-sniffer
      - type: volume
        source: log
        target: /var/log/mahjongsoul-sniffer
      - type: volume
        source: srv
        target: /srv/mahjongsoul-sniffer
    depends_on:
      - redis
    ports:
      - target: 8080
        published: ${PROXY_PORT:-8080}
        protocol: tcp
      - target: 5000
        published: ${WEB_SERVER_PORT:-5000}
        protocol: tcp
