---
redis:
  host: redis
  port: 6379
sniffer:
  logging:
    level: INFO
    file:
      path: /var/log/mahjongsoul-sniffer/api-visualizer/sniffer.log
      max_bytes: 10485760
      backup_count: 10
web_server:
  logging:
    level: INFO
    file:
      path: /var/log/mahjongsoul-sniffer/api-visualizer/web-server.log
      max_bytes: 10485760
      backup_count: 10
