logging:
  level: INFO
  log_file:
    path: output/game_abstract_archiver.log
    max_bytes: 10485760
    backup_count: 10
redis:
  host: redis
  port: 6379
s3:
  bucket: 98106a91-edae-4dbd-8fe3-daf39f28999b
  key_prefix: game_abstract/%Y/%m/%d
