---
yostar_login:
  email_address: user@example.net
redis:
  host: redis
  port: 6379
s3:
  bucket_name: 98106a91-edae-4dbd-8fe3-daf39f28999b
  authentication_email_key_prefix: authentication-email
  game_abstract_key_prefix: game-abstract/%Y/%m/%d
sniffer:
  logging:
    level: INFO
    file:
      path: /var/log/mahjongsoul-sniffer/game-abstract-crawler/sniffer.log
      max_bytes: 10485760
      backup_count: 10
    redis:
      key: log.sniffer
      max_entries: 100
archiver:
  logging:
    level: INFO
    file:
      path: /var/log/mahjongsoul-sniffer/game-abstract-crawler/archiver.log
      max_bytes: 10485760
      backup_count: 10
    redis:
      key: log.archiver
      max_entries: 100
crawler:
  retry_interval: 300
  logging:
    level: INFO
    file:
      path: /var/log/mahjongsoul-sniffer/game-abstract-crawler/crawler.log
      max_bytes: 10485760
      backup_count: 10
    redis:
      key: log.crawler
      max_entries: 100
