---
redis:
  host: redis
  port: 6379
interval: 3600
s3:
  bucket_name: 98106a91-edae-4dbd-8fe3-daf39f28999b
  game_abstract_key_prefixes:
    - game-abstract
    - game-abstract-alcyone
    - game-abstract-electra
  game_detail_key_prefix: game-detail
googleapi:
  client_id: 210659263154-7nqbe1qkh8v366f5866apn0kn8knni98.apps.googleusercontent.com
  client_secret: x2_vGcAkyjnmYXHi9OOy_Gqb
spreadsheet:
  id: 1MuwnHqf3rQVQbCq6JGm6Ud87Z6F-rp6MzkI8nAItDr8
  sheet_title: シート1
main:
  logging:
    level: INFO
    file:
      path: /var/log/mahjongsoul-sniffer/crawler-batch/main.log
      max_bytes: 10485760
      backup_count: 10
